### ISSUE TITLE
Mechanism to auto-install/auto-update gem

### ISSUE THREAD

**Issue by docwhat** [alexgenco/neovim-ruby#23]
Currently, if the neovim gem is not installed, I get this message:

```
$ vim
function provider#ruby#Call[8]..remote#host#Require[13]..provider#ruby#Require, line 10
Vim(if):Channel was closed by the client
rbenv: neovim-ruby-host: command not found
Failed to load ruby host. You can try to see what happened by starting Neovim with the environment variable $NVIM_RUBY_LOG_FILE set to a file and opening the generated log file.Also, the host stderr is available in messages.
Press ENTER or type command to continue
```

Instead, it would be nice if it did something like:

```
$ vim
Your ruby is missing the neovim gem.  Attempting to install...
Successfully installed the neovim gem
Press ENTER or type command to continue
```

[My configuration files](https://github.com/docwhat/dotfiles/tree/master/config/nvim)

**Comment by alexgenco** [comment]
This is a great idea, although I'm not sure we want to make assumptions about the way people install rubygems. Since this would be mostly an nvim-side change anyway, would you mind reopening this as an issue on [neovim](https://github.com/neovim/neovim/issues) to get some of their input? Feel free to mention me.
