### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by greyblake** [alexgenco/neovim-ruby#3]
Hi!
Thanks for the ruby client)
Are you gonna push it to rubygems as a gem?

**Comment by rjungemann** [comment]
What is the plan for making this a gem?

**Comment by jalcine** [comment]
I think it might be fair to say that @alexgenco's abandoned this project.

**Comment by alexgenco** [comment]
Sorry I'm not sure how I missed these comments. The project is more or less on hold. The main reason I haven't published it yet is that I'm waiting for msgpack-ruby to add support for extended types, which is [in progress](https://github.com/msgpack/msgpack-ruby/issues/42). Right now I'm using a fork from a pull request to get the functionality.

Tarruda also mentioned a neovim rpc c library that could be used through FFI. I'm not sure if that ever happened, but I would like to use that rather than the way I'm doing it here.

If anyone is looking to contribute, I good line of work would be to handle messages in a libuv event loop. When I attempted this before, libuv support didn't seem so great for ruby.

**Comment by jalcine** [comment]
[**@alexgenco**](https://github.com/alexgenco) commented on [Aug 5, 2015, 11:01 AM EDT](https://github.com/alexgenco/neovim-ruby/issues/3#issuecomment-128027497 "2015-08-05T15:01:52Z - Replied by Github Comment Enhancer"):
> Sorry I'm not sure how I missed these comments.

No worries; I apologize for the earlier comment, I only assumed because of the last time you've committed to this.

> The project is more or less on hold. The main reason I haven't published it yet is that I'm waiting for msgpack-ruby to add support for extended types, which is [in progress](https://github.com/msgpack/msgpack-ruby/issues/42). Right now I'm using a fork from a pull request to get the functionality.

Got it; I'll subscribe to that issue.

> Tarruda also mentioned a neovim rpc c library that could be used through FFI. I'm not sure if that ever happened, but I would like to use that rather than the way I'm doing it here.

Interesting as a stopgap until a full Ruby solution is available. I haven't used FFI much (I hear it's the bee's knees for binding libs together) but I'm willing to take a crack at it or review as needed.

> If anyone is looking to contribute, I good line of work would be to handle messages in a libuv event loop. When I attempted this before, libuv support didn't seem so great for ruby.

Is the code for this still hanging around re: libuv + ruby for the event loop? I've done work with the event loop in libuv but only in C++.

To be honest, going the FFI route might be the temporary option because that PR doesn't look too decisive in a solution as of yet.

**Comment by alexgenco** [comment]
@jalcine the libuv work is on a very old, abandoned [branch](https://github.com/alexgenco/neovim-ruby/blob/libuv/lib/neovim/stream.rb). You might be able to salvage something from this, but a complete rewrite might also be in order.

Later this week I'll try to look into the status of libnvim (it looks like it's [available now](https://github.com/neovim/neovim/blob/7dc241ac782e3a469d73d5f9a7baeba4e6107333/Makefile#L55-L56)), but feel free to take a crack at the FFI bindings if you'd like.

**Comment by ff2000** [comment]
Ta... daaaa!!!! :D
https://github.com/msgpack/msgpack-ruby/commit/61f3499d5c7f268b157710c1218c26cd6d6a0e57

**Comment by jalcine** [comment]
Oh, this changes everything! :fireworks:

**Comment by alexgenco** [comment]
Great timing! I'll bump the msgpack dep once they release it to rubygems.

**Comment by jalcine** [comment]
Thanks @alexgenco!

**Comment by alexgenco** [comment]
You all might be interested in this big PR I just opened: https://github.com/alexgenco/neovim-ruby/pull/4

**Comment by jfredett** [comment]
What's the status on this being released to rubygems? Did the dependency situation ever get resolved?

**Comment by alexgenco** [comment]
@jfredett I'm planning on getting a 0.0.1 up to rubygems tomorrow. The msgpack-ruby dependency is basically resolved (https://github.com/alexgenco/neovim-ruby/commit/f7f6ffa1a7da0849d4bec87605830a8e04b0830d), although I'd like to pin to a non-dev version as soon as it's available.

**Comment by jfredett** [comment]
@alexgenco Awesome! I'm looking forward to playing with this binding. Thanks!

**Comment by alexgenco** [comment]
v0.0.1 has been released to RubyGems. I'm going to close this; feel free to try out the gem and open new issues.

**Comment by greyblake** [comment]
Thanks!)
